UESLESS_OBJECTS =  screenshots saves \
	tv-cache assets/skins \
	logs crash-reports .mixin.out \
	pixelmon AudioBuffer mods/VoxelMods assets/galacticraftMaps customnpcs photo-frame-cache CustomSkinLoader viewview bendspacks \
	usercache.json usernamecache.json null
.PHONY=clean
clean:
	@rm -rf $(UESLESS_OBJECTS)

	
